swagger.openapi.entities:
  path: '/swagger/openapi/entities'
  defaults:
    _controller: '\Drupal\swagger\Controller\OpenApiController::entityResourcesJson'
  methods: [GET]
  requirements:
    _permission: 'access swagger api docs'
    _format: 'json'

swagger.openapi.non_entities:
  path: '/swagger/openapi/non-entity'
  defaults:
    _controller: '\Drupal\swagger\Controller\OpenApiController::nonBundleResourcesJson'
  methods: [GET]
  requirements:
    _permission: 'access swagger api docs'
    _format: 'json'

swagger.openapi.bundle:
  path: '/swagger/openapi/{entity_type}/{bundle_name}'
  defaults:
    _controller: '\Drupal\swagger\Controller\OpenApiController::bundleJson'
  methods: [GET]
  requirements:
    _permission: 'access swagger api docs'
    _format: 'json'

swagger.openapi.downloads:
  path: '/swagger/openapi/downloads'
  defaults:
    _controller: '\Drupal\swagger\Controller\OpenApiDownloadController::downloadsList'
  methods: [GET]
  requirements:
    _permission: 'access swagger api docs'


