swagger_ui.swaggerUI.non_entity:
  path: '/swagger/swagger-ui/non-entity'
  defaults:
    _controller: '\Drupal\swagger_ui\Controller\SwaggerUIController::nonEntityResources'
  methods: [GET]
  requirements:
    _permission: 'access swagger_ui api docs'

swagger_ui.swaggerUI.bundle:
  path: '/swagger/swagger-ui/{entity_type}/{bundle_name}'
  defaults:
    _controller: '\Drupal\swagger_ui\Controller\SwaggerUIController::bundleResource'
  methods: [GET]
  requirements:
    _permission: 'access swagger_ui api docs'

swagger_ui.swaggerUI.list:
  path: '/swagger/swagger-ui/list-resources'
  defaults:
    _controller: '\Drupal\swagger_ui\Controller\SwaggerUIController::listResources'
    _title: 'REST API'
  methods: [GET]
  requirements:
    _permission: 'access swagger_ui api docs'

